StoreApp/Component/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Component
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private readonly Cart _cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }
        public string Invoke()
        {
            return _cart.Lines.Count().ToString();
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.controller
{
    public class CategoryController : Controller
    {
        private IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.CategoryService.GetAllCategories(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.controller
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

         public IActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductWithDetails(p);
            var pagination = new Pagination()
            {
                CurrenPage = p.pageNumber,
                ItemsPerPage = p.pageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }


        public IActionResult Get([FromRoute(Name ="id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id,false);
            return View(model);
        }
    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center ">
                    <i class="fa-solid fa-store text-secondary display-6"></i>
                    <br />
                    <bold>BTK</bold> Akademi
                </div>
                <div class="text-muted text-center">
                    Store App
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2023 <br />BTK Akademi ASP.NET Core MVC Eğitimi
                </div>

                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>

            </div>
            <div class="col-md-2">
                <div products="" number="6"></div>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin")) // Login ise
{
    <li class="nav-item">
        <a class="nav-link" aria-current="page" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a>
    </li>
}


@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-route-returnUrl="@Context.Request.PathAndQuery()"
            asp-action="Logout">
            Logout</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-route-returnUrl="@Context.Request.PathAndQuery()"
            asp-action="Login">
            Login</a>
    </li>
}

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-light border-bottom navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="/">
      <i class="fa-solid fa-store fa-2x text-secondary"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">
            <i class="fa-solid fa-house"></i>
            Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" asp-controller="Product" asp-action="Index">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" asp-page="/Contact">Contact</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" asp-area="" asp-page="/Cart">
            <i class="fa-solid fa-cart-shopping"></i>
            Cart (@await Component.InvokeAsync("CartSummary"))
          </a>
        </li>

        <partial name="_LoginMenu">
      </ul>
    </div>
  </div>
</nav>

StoreApp/Views/Shared/_ProductCard.cshtml
@model Product
<div class="col-md-4 my-3">
    <div class="card" style="width: 18rem">

        <div class="card-header text-center">
            @Model.ProductName
        </div>

        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-text">
                <div class="text-danger text-center lead p-2 rounded-2">
                    @Model?.Price.ToString("C2")
                </div>
            </div>
            <p class="card-text">@Model?.Summary</p>
            <div class="d-flex justify-content-center">
                <div class="btn btn-group">
                    <a 
                    asp-controller="Product" asp-action="Get" asp-route-id="@Model?.ProductId" 
                    class="btn btn-outline-secondary">
                        <i class="fa-solid fa-arrow-right"></i>
                    </a>
                    <form id=@Model?.ProductId asp-page="/cart" method="post">  @* Bilgiyi Form ile göndericez *@
                        <input type="hidden" asp-for="ProductId" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit" class="btn btn-outline-secondary">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>