StoreApp/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles ="Admin")]

    public class RoleController : Controller
    {
        private readonly IServiceManager _manager;

        public RoleController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            return View(_manager.AuthService.Roles);
        }
    } 
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.controller
{
    public class CategoryController : Controller
    {
        private IServiceManager _manager;

        public CategoryController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.CategoryService.GetAllCategories(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Cart _cart;

        public OrderController(IServiceManager manager , Cart cart)
        {
            _manager = manager;
            _cart = cart;
            
        }

        [Authorize]
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        [ValidateAntiForgeryToken] // Güvenlik amaçlı sahteciliği önlemek için yapılır.

        public IActionResult Checkout([FromForm]Order order)
        {
            if(_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("","Sorry your cart is empty");
            }
            if(ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complate" , new {OrderId = order.OrderId});
            }
            else 
                return View(); // Mevcut sayfaya döner.
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.controller
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

         public IActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductWithDetails(p);
            var pagination = new Pagination()
            {
                CurrenPage = p.pageNumber,
                ItemsPerPage = p.pageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }


        public IActionResult Get([FromRoute(Name ="id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id,false);
            return View(model);
        }
    }
}

StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet " href="~/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet " href="~/css/site.css">
    <link rel="stylesheet " href="~/lib/font/awesome/css/all.css">
</head>

<body>
    <header>
        <partial name="_Navbar"></partial>
        @RenderSection("Top", false)
        <!-- RenderSection Sayfaların Top bölümünü false olduğu için görünmez yapar -->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer", false)
        <partial name="_Footer"/>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)<!-- Burası ne anlama geliyor bak -->
</body>

</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-dark border-bottom navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand text-black" href="/">Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
          <a class="nav-link text-black" aria-current="page" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" aria-current="page" asp-controller="Product" asp-action="Index">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" aria-current="page" asp-controller="Order" asp-action="Index">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" aria-current="page" asp-controller="Role" asp-action="Index">Roles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" aria-current="page" asp-controller="User" asp-action="Index">Users</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a target="_blank" class="nav-link text-black" aria-current="page" asp-area="" asp-controller="Home"
            asp-action="Index">
            <i class="fa-thin fa-house"></i>
            Web</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" aria-current="page" asp-area="" asp-controller="Account" asp-action="Logout">
            <i class="fa-solid fa-right-from-bracket"></i>
            Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>